export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES"
export const GET_ID_VIDEOGAME = "GET_ID_VIDEOGAME"
export const GET_NAME_VIDEOGAME = "GET_NAME_VIDEOGAME"
export const POST_NEW_VIDEOGAME = "POST_NEW_VIDEOGAME"

export const POST_ALL_GENRES = "POST_ALL_GENRES"

